clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 200

    # The number of clients selected in each round
    per_round: 50

    # Should the clients compute test accuracy locally?
    do_test: false

    random_seed: 1

    comm_simulation: true 
    compute_comm_time: true

server:
    address: 127.0.0.1
    port: 8015
    do_test: true
    random_seed: 1

    simulate_wall_time: true

data:
    # The training and testing dataset
    datasource:  Wikitext2
    data_path: /data/dixi
    sampler: iid
    testset_sampler: iid
##
##    # The random seed for sampling data
    random_seed: 1
    
    reload_data: true
    concurrent_download: true
    partition_size: 1631
    test_partition_size: 3837
    # 2088628 245569
trainer:
    # The type of the trainer
    type: basic

    rounds: 12

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # The target accuracy
    target_accuracy: 100

    # Number of epochs for local training in each communication round
    epochs: 1
    batch_size: 64
    loss_criterion: CrossEntropyLoss
    optimizer: SGD
    lr_scheduler: MultiStepLR
    global_lr_scheduler: true

    model_type: torch_hub
    model_name: transformer


algorithm:
    # A aggregation algorithm
    type: fedavg
    
results:
    types: round, accuracy, elapsed_time, comm_time, round_time, comm_overhead

parameters:
    model:
        model_rate: 1.
    optimizer:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0005
    learning_rate:
        milestone_steps: 3, 6
        gamma: 0.1
    limitation:
        activate: false

